server.port=8080
spring.main.web-application-type=servlet
client-azureopenai-key=${API_KEY}
client-azureopenai-endpoint=${API_ENDPOINT}
client-azureopenai-deployment-name=${DEPLOYMENT_NAME}

embeddings.collection-name: star_charts
embeddings.deployment-name: text-embedding-3-small-1
embeddings.vector-size: 4
embeddings.search-limit: 2