server.port=8080
spring.main.web-application-type=servlet
client-azureopenai-key=${API_KEY}
client-azureopenai-endpoint=${API_ENDPOINT}
client-azureopenai-deployment-name=${DEPLOYMENT_NAME}

embeddings.collection-name: data-collection
embeddings.deployment-name: text-embedding-3-small-1
embeddings.vector-size: 1536
embeddings.search-limit: 1
embeddings.init-docs-path: classpath:data/*